version: '2.1'

job_defaults: &job_defaults
  filters:
    tags:
      only: /.*/

orbs:
  github-cli: circleci/github-cli@2.4.0
  docker: circleci/docker@2.6.0
  codecov: codecov/codecov@4.1.0

executors:
  go:
    docker:
      - image: cimg/go:1.22

jobs:
  test:
    executor: go
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            gotestsum --junitfile unit-tests.xml
            make save-coverage-report
      - run:
          name: Get test coverage
          command: |
            go test -race -coverprofile=coverage.txt -covermode=atomic  -v ./...
      # Disabled for now
      # - codecov/upload
      - store_test_results:
          path: unit-tests.xml
      - store_artifacts:
          path: unit-tests.xml
      - store_artifacts:
          path: coverage.html

  build:
    executor: go
    steps:
      - checkout
      - run:
          name: Build binaries
          command: make build
      - persist_to_workspace:
          root: ./
          paths:
            - dist/

workflows:
  version: 2
  build:
    jobs:
      - test:
          <<: *job_defaults

      - build:
          <<: *job_defaults
          requires:
            - test
